import { solve, isClose } from "./solvers.js";
import { drawFigure } from "./diagrams.js";

const app = document.querySelector("#app");
const state = { catalog: null, exercise: null, mode: "learn", data: {}, attempts: {}, timer: null, seconds: 0, installPrompt: null };
const modes = { learn: "Apprentissage", train: "Entraînement", exam: "Examen" };
const pedagogy = {
  density:{hypotheses:"Fluide homogène ; g = 9,81 m/s² ; la densité est définie par rapport à l’eau à ρeau = 1000 kg/m³.",why:["Le poids est une force. On le convertit d’abord en newtons, puis on utilise W = mg.","La masse volumique mesure la masse contenue par unité de volume.","Le poids volumique est le poids par unité de volume ; son unité est ici le kN/m³.","La densité est un rapport de deux masses volumiques : elle n’a donc pas d’unité."],check:"Pour une huile, on attend généralement ρ < 1000 kg/m³ et d < 1."},
  viscosity:{hypotheses:"Fluide newtonien ; écoulement de Couette permanent ; adhérence aux deux plaques ; profil de vitesse linéaire.",why:["Toutes les longueurs doivent être en mètres avant d’utiliser les unités SI.","La contrainte est la force tangentielle rapportée à la surface sollicitée.","Le profil étant linéaire, le gradient de vitesse vaut U/e. La loi de Newton relie ce gradient à τ.","La viscosité cinématique compare les effets visqueux à l’inertie volumique du fluide."],check:"μ doit être positive et ν = μ/ρ doit avoir l’unité m²/s."},
  compressibility:{hypotheses:"Compression isotherme, masse d’eau conservée et module d’élasticité K supposé constant sur l’intervalle de pression.",why:["Le module utilise une variation de pression : il faut donc soustraire la pression initiale à la pression finale.","Le signe négatif de ΔV traduit une diminution. On présente ici sa valeur absolue pour éviter toute ambiguïté.","On applique la diminution relative au volume initial.","Le volume final doit être légèrement inférieur au volume initial, car l’eau est peu compressible."],check:"Même sous plusieurs dizaines de bars, la variation de volume de l’eau reste généralement inférieure à quelques pourcents."},
  pressureDepth:{hypotheses:"Fluide au repos, masse volumique constante, axe vertical et pression atmosphérique uniforme à la surface.",why:["La relation fondamentale de l’hydrostatique donne une augmentation ρgh lorsqu’on descend.","La pression absolue est mesurée depuis le vide ; elle est égale à la pression relative plus la pression atmosphérique."],check:"La pression absolue doit être supérieure à la pression atmosphérique et à la pression relative."},
  layeredPressure:{hypotheses:"Deux fluides non miscibles au repos ; réservoir ouvert ; pression continue à l’interface.",why:["En descendant dans l’huile, la pression augmente de ρhuileghhuile.","La pression est continue à l’interface ; on ajoute ensuite l’accroissement dans l’eau.","La hauteur équivalente exprime la pression totale comme une colonne d’eau fictive."],check:"La contribution de chaque couche doit être positive et proportionnelle à sa masse volumique et à son épaisseur."},
  manometer:{hypotheses:"Fluides au repos ; deux prises à la même cote ; eau et mercure non miscibles ; effets capillaires négligés.",why:["On chemine d’une prise à l’autre : la pression augmente en descendant et diminue en montant.","Les colonnes d’eau communes se compensent ; il reste l’effet de la différence de masse volumique.","Diviser par ρeaug convertit la différence de pression en mètres de colonne d’eau."],check:"Le côté où le mercure est le plus bas correspond à la pression la plus élevée."},
  planeForce:{hypotheses:"Paroi verticale plane, surface libre à pression atmosphérique, eau au repos, pression relative utilisée.",why:["La pression varie linéairement avec la profondeur ; le centre géométrique est à H/2.","La résultante est la pression au centre de gravité multipliée par l’aire.","Le moment quadratique décrit la répartition de la surface autour de son centre.","Comme la pression augmente vers le bas, le centre de poussée est sous le centre géométrique."],check:"Pour une paroi rectangulaire affleurante, yₚ = 2H/3 exactement."},
  submergedGate:{hypotheses:"Vanne verticale plane entièrement immergée ; liquide au repos ; pression atmosphérique identique des deux côtés hors liquide.",why:["La profondeur moyenne est celle du centre de gravité de la vanne.","On intègre la pression hydrostatique sur l’aire, ce qui donne F = ρgAȳ.","La position résulte de l’égalité des moments de la distribution de pression et de la résultante."],check:"Le centre de poussée doit être sous le centre de gravité, mais rester à l’intérieur de la vanne."},
  venturi:{hypotheses:"Écoulement permanent, eau incompressible, Venturi horizontal, fluide parfait et pertes négligées.",why:["On convertit les diamètres en mètres avant de calculer les sections circulaires.","Le manomètre fournit directement la différence de pression entre l’entrée et le col.","La conservation de la masse impose le même débit dans les deux sections.","Bernoulli traduit la conservation de l’énergie mécanique entre 1 et 2.","On remplace V₁ et V₂ par Q/S puis on isole Q dans l’équation obtenue.","La section du col étant plus petite, sa vitesse doit être plus grande."],check:"V₂/V₁ doit être égal à S₁/S₂ = (D₁/D₂)² et p₂ doit être inférieur à p₁."},
  torricelli:{hypotheses:"Réservoir de grande section, surface et orifice à pression atmosphérique, vitesse de surface négligeable.",why:["L’aire de l’orifice est calculée après conversion du diamètre en mètres.","Bernoulli donne √(2gh) ; le coefficient Cᵈ corrige la contraction et les pertes réelles.","Le débit volumique est le produit de la section par la vitesse moyenne réelle."],check:"Cᵈ < 1 implique une vitesse et un débit réels inférieurs aux valeurs idéales."},
  jetPlate:{hypotheses:"Régime permanent ; jet libre à pression atmosphérique ; plaque fixe ; pertes dans l’impact négligées pour le bilan axial.",why:["La section du jet se calcule avec son diamètre en mètres.","Le débit est constant jusqu’à l’impact.","Après déviation tangentielle, la composante de vitesse normale à la plaque devient nulle.","Le théorème de quantité de mouvement donne l’effort F = ρQV."],check:"L’effort varie comme V² : doubler la vitesse multiplie la force par quatre."},
  jetDeflect:{hypotheses:"Auget fixe, jet libre, norme de la vitesse conservée et pression atmosphérique à l’entrée comme à la sortie.",why:["Le débit permet d’obtenir le débit massique ṁ = ρQ.","La force est liée à la différence vectorielle entre les vitesses d’entrée et de sortie.","La géométrie du triangle des vitesses donne |ΔV| = 2V sin(θ/2)."],check:"À θ = 0°, la force tend vers zéro ; à θ = 180°, elle tend vers 2ρQV."},
  colebrook:{hypotheses:"Écoulement permanent établi dans une conduite circulaire pleine ; eau incompressible ; facteur de Darcy utilisé.",why:["On convertit D, Q, ε et ν en SI puis on déduit la vitesse moyenne.","Re compare l’inertie aux effets visqueux et détermine le régime.","En turbulent, Colebrook est implicite : on répète le calcul jusqu’à stabilisation de λ.","Darcy–Weisbach transforme le frottement réparti en perte de charge."],check:"λ est généralement compris entre 0,01 et 0,08 en conduite ; h_f doit être positive."},
  minorLosses:{hypotheses:"Écoulement permanent ; même diamètre et même vitesse de référence dans toutes les singularités.",why:["La vitesse moyenne se déduit du débit et de la section.","Les pertes locales s’additionnent lorsque les coefficients utilisent la même vitesse de référence.","Chaque singularité dissipe K·V²/(2g) ; la somme donne la perte totale."],check:"Les pertes varient comme V² : une réduction du débit est très efficace pour les diminuer."},
  coaxialViscometer:{hypotheses:"Entrefer mince ; fluide newtonien ; le cylindre intérieur tourne, l’extérieur est fixe ; profil de Couette localement plan.",why:["La vitesse angulaire convertit N en rad/s.","La vitesse périphérique est celle de la paroi intérieure.","L’entrefer est la différence des deux rayons.","Le couple mesuré équilibre le moment de la contrainte visqueuse.","On isole μ à partir de C = τ(2πRᵢL)Rᵢ et τ = μU/e."],check:"μ doit être positive. Un entrefer trop grand invalide l’approximation de Couette plan."},
  capillary:{hypotheses:"Tube circulaire fin ; équilibre statique ; tension superficielle uniforme ; pesanteur constante.",why:["La composante verticale de la tension superficielle équilibre le poids de la colonne.","La loi de Jurin donne h = 4σ cosθ /(ρgd)."],check:"Un liquide mouillant (θ < 90°) monte ; le mercure (θ > 90°) descend. h diminue si d augmente."},
  laplace:{hypotheses:"Interface sphérique unique (goutte) ou double (bulle de savon) ; tension superficielle constante.",why:["Le rayon doit être exprimé en mètres.","La loi de Laplace relie la surpression au rayon de courbure : Δp = nσ/R."],check:"Plus la goutte est petite, plus la surpression est grande. Une bulle de savon a deux interfaces."},
  idealGas:{hypotheses:"Air assimilé à un gaz parfait ; pression et température absolues.",why:["La température Celsius est convertie en kelvin.","La pression est convertie en pascals.","ρ = p/(RT) pour un gaz parfait."],check:"À 20 °C et 1 bar, on attend ρ ≈ 1,2 kg/m³ pour l’air."},
  hydraulicPress:{hypotheses:"Liquide incompressible au repos ; principe de Pascal ; conservation du volume déplacé.",why:["Le rapport des surfaces vaut le carré du rapport des diamètres.","Pascal : F₁/A₁ = F₂/A₂.","Le volume chassé se conserve : A₁x₁ = A₂x₂."],check:"Le petit piston parcourt une course beaucoup plus grande que le grand."},
  circularGate:{hypotheses:"Vanne circulaire verticale entièrement immergée ; fluide au repos ; pression relative.",why:["L’aire d’un disque est πD²/4.","La résultante est ρgAȳ.","Iᴳ = πD⁴/64 pour un disque.","Le centre de poussée est sous le centre géométrique."],check:"yₚ > ȳ et l’écart diminue quand la vanne est très profonde."},
  bargeStability:{hypotheses:"Barge parallélépipédique ; petites inclinaisons ; eau au repos ; pas de surfaces libres internes.",why:["Le volume déplacé est le volume immergé.","À l’équilibre, le poids égale la poussée d’Archimède.","Le centre de carène d’un ponton rectangulaire est à Te/2.","BM = I/∇ avec I = LB³/12.","GM = KB + BM − KG."],check:"GM > 0 : stable ; GM < 0 : instable au roulis."},
  pipeContinuity:{hypotheses:"Fluide incompressible ; régime permanent ; section circulaire pleine.",why:["La section se calcule après conversion du diamètre en mètres.","La vitesse moyenne est le débit divisé par la section.","Inverser Q = V·πD²/4 donne le diamètre qui réalise une vitesse cible."],check:"En AEP, on vise souvent 0,5 à 1,5 m/s. Une vitesse trop grande signale un diamètre insuffisant."},
  twoSectionContinuity:{hypotheses:"Fluide incompressible ; régime permanent ; un seul tube de courant, sans fuite latérale.",why:["Chaque section circulaire se calcule avec son diamètre.","La conservation du débit impose Q = A₁V₁ = A₂V₂.","Si le diamètre est divisé par 2, la vitesse est multipliée par 4."],check:"V₂/V₁ doit valoir (D₁/D₂)². Une vitesse aval > 3 m/s est souvent excessive en réseau."},
  networkNode:{hypotheses:"Fluide incompressible ; régime permanent ; nœud sans accumulation.",why:["Les débits entrants se déduisent de Q = AV.","La loi des nœuds impose ΣQ = 0.","Le débit restant traverse la conduite 3 et fixe sa vitesse."],check:"Q₃ doit rester positif. Une vitesse trop faible dans D₃ indique un diamètre surdimensionné."},
  convectiveAcceleration:{hypotheses:"Régime permanent ; vitesse unidimensionnelle variant linéairement le long du convergent.",why:["L’accélération locale ∂V/∂t est nulle.","Il reste le terme convectif V·dV/dx.","Au milieu, V est la moyenne des deux extrémités."],check:"Même en régime permanent, a peut atteindre plusieurs g dans un convergent court."},
  reservoirRise:{hypotheses:"Fluide incompressible ; débits constants ; surface libre horizontale ; section du réservoir constante.",why:["Le bilan de volume relie la montée du plan d’eau au débit net.","dh/dt = (Qₑ − Qₛ)/A.","Le temps est Δh divisé par cette vitesse de montée."],check:"Si Qₑ < Qₛ le niveau baisse. Un grand diamètre ralentit fortement la variation de niveau."},
  tankFilling:{hypotheses:"Débit constant ; conduite circulaire pleine ; vitesse limitée par une consigne de réseau.",why:["Le débit est le volume à livrer divisé par la durée.","La section minimale est Q/Vmax.","On en déduit le plus petit diamètre acceptable."],check:"On arrondit ensuite D au diamètre commercial supérieur."},
  distributedFlow:{hypotheses:"Prélèvement uniformément réparti ; régime permanent ; fluide incompressible.",why:["Le débit prélevé est la différence entre l’entrée et la sortie.","Le débit linéique est ce volume divisé par la longueur.","À mi-parcours, la moitié du prélèvement a déjà eu lieu."],check:"Si tout le débit est distribué, Qₛ = 0 et Q(L) = 0."},
  bernoulliSections:{hypotheses:"Fluide parfait incompressible ; régime permanent ; une ligne de courant ; pas de machine entre 1 et 2.",why:["Les vitesses viennent de la continuité.","Bernoulli convertit cote, pression et énergie cinétique.","La pression chute si on s’élève ou si le fluide accélère."],check:"p₂ doit rester positive en relatif si la conduite n’est pas en dépression."},
  drainTime:{hypotheses:"Réservoir cylindrique ; orifice en mince paroi ; régime quasi permanent ; Cᵈ constant.",why:["On calcule d’abord les deux sections.","Le bilan −A dh/dt = Cᵈ a √(2gh) se sépare.","L’intégration entre h₁ et h₂ donne le temps."],check:"La vidange totale (h₂ = 0) dure deux fois plus longtemps qu’à débit initial constant."},
  pitot:{hypotheses:"Point d’arrêt ; même cote ; fluide parfait ; le manomètre mesure p₀ − p.",why:["Le mercure convertit la dénivellation en Δp = (ρₘ − ρ)gΔh.","Bernoulli entre l’écoulement et le point d’arrêt donne V = √(2Δp/ρ)."],check:"C’est une vitesse locale, en général maximale à l’axe. Le débit demande un coefficient de profil."},
  siphon:{hypotheses:"Fluide parfait ; diamètre constant ; réservoir de grande section ; surfaces libre et sortie à pₐₜₘ.",why:["Entre surface et sortie, Bernoulli se réduit à V = √(2gΔz).","Le débit suit de la section.","Au point haut, la hauteur cinétique et z_C se paient en dépression."],check:"p_C doit rester nettement au-dessus de la pression de vapeur (~2,3 kPa à 20 °C), sinon cavitation."},
  hydraulicPower:{hypotheses:"Surfaces libres à l’atmosphère et de grande section ; Bernoulli généralisé entre les deux plans d’eau.",why:["HMT = hauteur géométrique + pertes déjà estimées.","La puissance hydraulique est ρgQH.","La puissance absorbée se déduit par le rendement."],check:"Sans pertes, HMT = H_g. Les pertes du chapitre 6 augmenteront Pₕ et P_abs."},
  froudeSimilarity:{hypotheses:"Similitude géométrique complète, même pesanteur sur le modèle et le prototype, écoulement à surface libre dominé par inertie et gravité.",why:["La similitude de Froude conserve le rapport entre forces d’inertie et de pesanteur.","Avec la même gravité, l’échelle des vitesses est la racine carrée de l’échelle des longueurs.","On applique cette échelle à la vitesse mesurée sur le modèle.","Un débit est une vitesse multipliée par une aire : λQ = λVλL².","Le débit modèle est d’abord converti de L/s en m³/s."],check:"Le prototype est plus grand : ses échelles de vitesse et de débit doivent être supérieures à 1."},
  manningChannel:{hypotheses:"Écoulement permanent uniforme, canal prismatique rectangulaire, pente faible et profondeur constante.",why:["Seules les parois en contact avec l’eau forment le périmètre mouillé ; la surface libre n’en fait pas partie.","Le rayon hydraulique représente l’efficacité hydraulique de la section.","En régime uniforme, la pente de fond égale la pente de la ligne d’énergie.","Le débit est la vitesse moyenne multipliée par la section mouillée.","Froude compare la vitesse de l’écoulement à la célérité des ondes de gravité."],check:"Fr < 1 indique un régime fluvial ; Fr > 1 un régime torrentiel ; Fr = 1 le régime critique."}
};

const equationSheets={density:["W = mg","ρ = m/𝒱","γ = ρg","d = ρ/ρeau"],viscosity:["τ = F/A","τ = μU/e","ν = μ/ρ"],coaxialViscometer:["ω = 2πN/60","U = ωRᵢ","τ = μU/e","C = τ(2πRᵢL)Rᵢ"],compressibility:["K = −Δp/(Δ𝒱/𝒱)","Δp = p₂−p₁"],capillary:["h = 4σcosθ/(ρgd)"],laplace:["Goutte : Δp = 2σ/R","Bulle : Δp = 4σ/R"],idealGas:["p = ρRT","T(K) = T(°C)+273,15"],pressureDepth:["p−pₐₜₘ = ρgh","pabs = pₐₜₘ+ρgh"],layeredPressure:["Δp = ρgΔh","p_fond = Σρᵢghᵢ"],manometer:["Descente : +ρgΔz","Montée : −ρgΔz"],hydraulicPress:["F₁/A₁ = F₂/A₂","A₁x₁ = A₂x₂"],planeForce:["F = ρgAȳ","yₚ = ȳ+Iᴳ/(Aȳ)"],submergedGate:["ȳ = y₀+H/2","F = ρgAȳ","yₚ = ȳ+Iᴳ/(Aȳ)"],circularGate:["A = πD²/4","Iᴳ = πD⁴/64","F = ρgAȳ"],bargeStability:["BM = I/∇","GM = KB+BM−KG","Stable si GM > 0"],venturi:["Q = S₁V₁ = S₂V₂","p/ρg+V²/2g+z = cte","Δp = (ρm−ρ)gΔh"],torricelli:["V = Cᵈ√(2gh)","Q = SV"],jetPlate:["ΣF⃗ = ṁ(V⃗₂−V⃗₁)","F = ρQV"],jetDeflect:["F = 2ρQVsin(θ/2)"],colebrook:["Re = VD/ν","1/√λ = −2log₁₀[ε/(3,7D)+2,51/(Re√λ)]","h_f = λ(L/D)V²/(2g)"],minorLosses:["h_s = ΣK·V²/(2g)"],froudeSimilarity:["Fr = V/√(gL)","λV = √λL","λQ = λL^(5/2)"],manningChannel:["R = A/P","V = KₛR^(2/3)√S","Fr = V/√(gy)"],pipeContinuity:["Q = AV","A = πD²/4","D = √(4Q/πV)"],twoSectionContinuity:["Q = A₁V₁ = A₂V₂","A = πD²/4","V₂/V₁ = (D₁/D₂)²"],networkNode:["Q = AV","ΣQₑ = ΣQₛ","V₃ = Q₃/A₃"],convectiveAcceleration:["a = ∂V/∂t + V·dV/dx","permanent : a = V dV/dx"],reservoirRise:["A dh/dt = Qₑ − Qₛ","t = AΔh/(Qₑ − Qₛ)"],tankFilling:["Q = 𝒱/t","A = Q/V","D = √(4A/π)"],distributedFlow:["Q(x) = Qₑ − qx","q = (Qₑ − Qₛ)/L"],bernoulliSections:["Q = A₁V₁ = A₂V₂","p/ρg + V²/2g + z = cte"],drainTime:["−A dh/dt = Cᵈa√(2gh)","t = 2A(√h₁−√h₂)/(Cᵈa√(2g))"],pitot:["Δp = (ρₘ − ρ)gΔh","V = √(2Δp/ρ)"],siphon:["V = √(2gΔz)","p_C = pₐₜₘ − ρg(z_C + V²/2g)"],hydraulicPower:["HMT = H_g + h_pertes","Pₕ = ρgQH","P_abs = Pₕ/η"]};
const esc = value => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const parse = value => Number(String(value).trim().replace(",", ".").replace(/\s/g, ""));
const randomValue = v => Number((Math.round((v.min + Math.random() * (v.max - v.min)) / v.step) * v.step).toFixed(8));
const formatTime = seconds => `${String(Math.floor(seconds / 60)).padStart(2,"0")}:${String(seconds % 60).padStart(2,"0")}`;
const toast = text => { const el = document.querySelector("#toast"); el.textContent = text; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 1800); };

function home() {
  stopTimer(); state.exercise = null;
  const total = state.catalog.exercises.length;
  app.innerHTML = `<section class="hero"><p class="eyebrow">Mécanique des fluides · Génie civil</p><h1>Comprendre, calculer, vérifier.</h1><p>Des exercices paramétriques fidèles au polycopié, avec unités, validation tolérante et correction raisonnée.</p><div class="signature">École Nationale d’Ingénieurs de Sfax<br><strong>Dr Ahmed Ksentini</strong></div></section><div class="section-title"><div><h2>Choisir un chapitre</h2><p>${total} exercices paramétriques, alignés sur le polycopié du S1.</p></div></div><section class="chapter-grid">${state.catalog.chapters.map(ch => { const count = state.catalog.exercises.filter(e => e.chapter === ch.id).length; return `<button class="chapter" data-chapter="${ch.id}"><span class="num">${ch.number}</span><h3>${esc(ch.title)}</h3><p>${esc(ch.description)}</p><span class="count">${count} exercice${count>1?"s":""} →</span></button>`; }).join("")}</section>`;
  document.querySelectorAll("[data-chapter]").forEach(button => button.addEventListener("click", () => chapterPage(button.dataset.chapter)));
  history.replaceState({}, "", location.pathname);
}

function chapterPage(chapterId) {
  const chapter = state.catalog.chapters.find(c => c.id === chapterId), exercises = state.catalog.exercises.filter(e => e.chapter === chapterId);
  app.innerHTML = `<button class="back" id="backHome">← Tous les chapitres</button><section class="chapter-banner"><span class="num">${chapter.number}</span><div><h1>${esc(chapter.title)}</h1><p>${esc(chapter.description)}</p></div></section><div class="section-title"><div><h2>Exercices</h2><p>Choisissez une situation puis un mode de travail.</p></div></div><section class="exercise-list">${exercises.map((e,i)=>`<button class="exercise-card" data-exercise="${e.id}"><span class="exercise-index">${String(i+1).padStart(2,"0")}</span><span><strong>${esc(e.title)}</strong><small>Niveau ${e.difficulty} · données paramétriques</small></span><span class="arrow">→</span></button>`).join("")}</section>`;
  document.querySelector("#backHome").addEventListener("click", home);
  document.querySelectorAll("[data-exercise]").forEach(b => b.addEventListener("click",()=>openExercise(state.catalog.exercises.find(e=>e.id===b.dataset.exercise))));
}

function openExercise(exercise, mode = state.mode) {
  stopTimer(); state.exercise = exercise; state.mode = mode; state.attempts = {};
  state.data = Object.fromEntries(exercise.variables.map(v => [v.key, mode === "learn" ? v.value : randomValue(v)]));
  renderExercise();
  if (mode === "exam") startTimer();
  history.replaceState({}, "", `#${exercise.id}`);
}

function renderExercise() {
  const e = state.exercise, chapter = state.catalog.chapters.find(c => c.id === e.chapter);
  app.innerHTML = `<section class="exercise-head"><div><button class="back" id="back">← Exercices du chapitre</button><h1>${esc(e.title)}</h1><p>Chapitre ${chapter.number} · Niveau ${e.difficulty}</p></div><div><div class="mode-switch" aria-label="Mode de travail">${Object.entries(modes).map(([key,label]) => `<button data-mode="${key}" class="${state.mode===key?"active":""}">${label}</button>`).join("")}</div><div id="clock" class="exam-clock">${state.mode === "exam" ? "Temps 00:00" : ""}</div></div></section><section class="workspace"><div><article class="card"><h2>Énoncé</h2><p class="statement">${esc(e.statement)}</p><div class="data-grid">${e.variables.map(v => `<div class="field"><label for="v_${v.key}">${esc(v.label)}</label><div class="input-wrap"><input id="v_${v.key}" data-variable="${v.key}" type="number" step="any" value="${state.data[v.key]}" ${state.mode === "exam" ? "readonly" : ""}><span class="unit">${v.unit}</span></div></div>`).join("")}</div><div class="actions">${state.mode !== "learn" ? `<button class="secondary" id="randomize">↻ Nouvelles données</button>` : ""}</div></article><article class="card"><h2>Schéma de l’exercice</h2><div class="diagram" id="diagram"></div><p class="diagram-note" id="diagramNote"></p></article></div><div><article class="card"><h2>${state.mode === "exam" ? "Votre copie" : "Résolution guidée"}</h2><div id="questions">${e.questions.map((q,i) => question(q,i)).join("")}</div><div class="actions"><button class="primary" id="submitAll">${state.mode === "exam" ? "Rendre la copie" : "Tout vérifier"}</button>${state.mode !== "exam" ? `<button class="secondary" id="showCorrection">Voir la correction</button>` : ""}</div><div id="score"></div></article><article class="card correction" id="correction" hidden></article></div></section>`;
  const formulas=equationSheets[e.solver]||["Consulter les hypothèses et établir le bilan fondamental."];
  app.querySelector(".workspace > div:nth-child(2)").insertAdjacentHTML("afterbegin",`<article class="card equation-card"><h2>Équations utiles</h2><p class="equation-intro">Rappel littéral — identifiez chaque grandeur avant de remplacer les valeurs.</p>${formulas.map(f=>`<div class="equation-line">${esc(f)}</div>`).join("")}</article>`);
  bindExerciseEvents();
  refreshDiagram();
}

function question(q, i) { return `<div class="question"><div class="question-title">${i+1}. ${esc(q.label)}</div><div class="answer-row"><div class="input-wrap"><input id="a_${q.key}" data-answer="${q.key}" inputmode="decimal" autocomplete="off" placeholder="Votre réponse"><span class="unit">${q.unit}</span></div>${state.mode !== "exam" ? `<button class="ghost" data-check="${q.key}">Vérifier</button>` : ""}</div><p class="feedback" id="f_${q.key}"></p></div>`; }

function readData() { state.exercise.variables.forEach(v => state.data[v.key] = parse(document.querySelector(`#v_${v.key}`).value)); }
function check(key) {
  readData(); const target = solve(state.exercise, state.data).values[key], input = document.querySelector(`#a_${key}`), value = parse(input.value), feedback = document.querySelector(`#f_${key}`);
  state.attempts[key] = (state.attempts[key] || 0) + 1;
  const correct = isClose(value, target); feedback.className = `feedback ${correct ? "good" : "bad"}`;
  feedback.innerHTML = correct ? "✓ Correct — unité et ordre de grandeur cohérents." : `✕ À revoir.${state.mode === "learn" && state.attempts[key] > 1 ? `<span class="hint">Indice : commencez par convertir toutes les données en SI et écrivez la relation littérale.</span>` : ""}`;
  return correct;
}
function submitAll() {
  const correct = state.exercise.questions.filter(q => check(q.key)).length, total = state.exercise.questions.length, score = 20 * correct / total;
  document.querySelector("#score").innerHTML = `<p class="score">Résultat : ${correct}/${total} — ${score.toLocaleString("fr-FR",{maximumFractionDigits:1})}/20</p>`;
  if (state.mode === "exam") { stopTimer(); showCorrection(); document.querySelector("#showCorrection")?.remove(); }
}
function showCorrection() {
  readData(); const result = solve(state.exercise, state.data), box = document.querySelector("#correction");
  const guide = pedagogy[state.exercise.solver] || {hypotheses:"Grandeurs exprimées dans le Système International.",why:[],check:"Vérifier les unités et l’ordre de grandeur."};
  box.hidden = false; box.innerHTML = `<h2>Correction détaillée</h2><section class="reasoning"><h3>1. Hypothèses et modèle physique</h3><p>${esc(guide.hypotheses)}</p></section><section class="given-data"><h3>2. Données de l’énoncé</h3><div class="data-summary">${state.exercise.variables.map(v=>`<span><small>${esc(v.label)}</small><strong>${esc(state.data[v.key])} ${v.unit}</strong></span>`).join("")}</div><p class="method-note">Avant tout calcul, les millimètres, litres, bars et kilopascals sont convertis en unités SI. Le calcul littéral est écrit avant le remplacement numérique.</p></section><h3>3. Résolution raisonnée</h3>${result.steps.map((s,i) => `<div class="solution-step" data-step="${i+1}"><h3>${esc(s[0])}</h3>${guide.why[i]?`<p class="explanation">${esc(guide.why[i])}</p>`:""}<p class="formula">${esc(s[1])}</p></div>`).join("")}<div class="final-result"><strong>4. Résultats numériques</strong><br>${state.exercise.questions.map(q => `${esc(q.label)} = <strong>${Number(result.values[q.key]).toLocaleString("fr-FR",{maximumSignificantDigits:5})} ${q.unit}</strong>`).join("<br>")}</div><section class="sanity-check"><h3>5. Interprétation et contrôle</h3><p>${esc(guide.check)}</p><p>Contrôle d’unités : chaque résultat est donné dans l’unité demandée. Il faut toujours conserver davantage de chiffres pendant le calcul et n’arrondir qu’à la fin.</p></section>`; box.scrollIntoView({behavior:"smooth",block:"start"});
}
function bindExerciseEvents() {
  document.querySelector("#back").addEventListener("click", () => chapterPage(state.exercise.chapter));
  document.querySelectorAll("[data-mode]").forEach(b => b.addEventListener("click", () => openExercise(state.exercise, b.dataset.mode)));
  document.querySelectorAll("[data-variable]").forEach(input => input.addEventListener("input", () => { readData(); refreshDiagram(); document.querySelector("#correction").hidden = true; }));
  document.querySelectorAll("[data-check]").forEach(b => b.addEventListener("click", () => check(b.dataset.check)));
  document.querySelector("#submitAll").addEventListener("click", submitAll);
  document.querySelector("#showCorrection")?.addEventListener("click", showCorrection);
  document.querySelector("#randomize")?.addEventListener("click", () => openExercise(state.exercise, state.mode));
}

function refreshDiagram() {
  if (!state.exercise) return;
  const figure = drawFigure(state.exercise.solver, state.data);
  const box = document.querySelector("#diagram");
  const note = document.querySelector("#diagramNote");
  if (box) box.innerHTML = figure.svg;
  if (note) note.textContent = figure.caption;
}

function startTimer() { state.seconds = 0; state.timer = setInterval(() => { state.seconds++; const clock = document.querySelector("#clock"); if (clock) clock.textContent = `Temps ${formatTime(state.seconds)}`; }, 1000); }
function stopTimer() { clearInterval(state.timer); state.timer = null; }

document.querySelector("#homeButton").addEventListener("click", home);
window.addEventListener("hashchange", () => {
  if (!state.catalog) return;
  const requested = state.catalog.exercises.find(e => `#${e.id}` === location.hash);
  if (requested) openExercise(requested);
  else if (!location.hash) home();
});
window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); state.installPrompt = event; const b = document.querySelector("#installButton"); b.hidden = false; b.onclick = async () => { await state.installPrompt.prompt(); b.hidden = true; }; });
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));

const loadJson = url => fetch(url).then(r => r.ok ? r.json() : []);
try {
  const [catalog, batch12, batch34] = await Promise.all([
    fetch("./data/exercises.json").then(r => r.json()),
    loadJson("./data/exercises-ch1-ch2.json"),
    loadJson("./data/exercises-ch3-ch4.json")
  ]);
  state.catalog = { ...catalog, exercises: [...catalog.exercises, ...batch12, ...batch34] };
  const requested = state.catalog.exercises.find(e => `#${e.id}` === location.hash);
  requested ? openExercise(requested) : home();
} catch {
  app.innerHTML = `<section class="card"><h1>Chargement impossible</h1><p>Lancez l’application depuis un serveur web local ou depuis Cloudflare Pages.</p></section>`;
}
