import { solve, isClose } from "./solvers.js";

const app = document.querySelector("#app");
const state = { catalog: null, exercise: null, mode: "learn", data: {}, attempts: {}, timer: null, seconds: 0, installPrompt: null };
const modes = { learn: "Apprentissage", train: "Entraînement", exam: "Examen" };
const pedagogy = {
  density:{hypotheses:"Fluide homogène ; g = 9,81 m/s² ; la densité est définie par rapport à l’eau à ρeau = 1000 kg/m³.",why:["Le poids est une force. On le convertit d’abord en newtons, puis on utilise W = mg.","La masse volumique mesure la masse contenue par unité de volume.","Le poids volumique est le poids par unité de volume ; son unité est ici le kN/m³.","La densité est un rapport de deux masses volumiques : elle n’a donc pas d’unité."],check:"Pour une huile, on attend généralement ρ < 1000 kg/m³ et d < 1."},
  viscosity:{hypotheses:"Fluide newtonien ; écoulement de Couette permanent ; adhérence aux deux plaques ; profil de vitesse linéaire.",why:["Toutes les longueurs doivent être en mètres avant d’utiliser les unités SI.","La contrainte est la force tangentielle rapportée à la surface sollicitée.","Le profil étant linéaire, le gradient de vitesse vaut U/e. La loi de Newton relie ce gradient à τ.","La viscosité cinématique compare les effets visqueux à l’inertie volumique du fluide."],check:"μ doit être positive et ν = μ/ρ doit avoir l’unité m²/s."},
  compressibility:{hypotheses:"Compression isotherme, masse d’eau conservée et module d’élasticité K supposé constant sur l’intervalle de pression.",why:["Le module utilise une variation de pression : il faut donc soustraire la pression initiale à la pression finale.","Le signe négatif de ΔV traduit une diminution. On présente ici sa valeur absolue pour éviter toute ambiguïté.","On applique la diminution relative au volume initial.","Le volume final doit être légèrement inférieur au volume initial, car l’eau est peu compressible."],check:"Même sous plusieurs dizaines de bars, la variation de volume de l’eau reste généralement inférieure à quelques pourcents."},
  pressureDepth:{hypotheses:"Fluide au repos, masse volumique constante, axe vertical et pression atmosphérique uniforme à la surface.",why:["La relation fondamentale de l’hydrostatique donne une augmentation ρgh lorsqu’on descend.","La pression absolue est mesurée depuis le vide ; elle est égale à la pression relative plus la pression atmosphérique."],check:"La pression absolue doit être supérieure à la pression atmosphérique et à la pression relative."},
  layeredPressure:{hypotheses:"Deux fluides non miscibles au repos ; réservoir ouvert ; pression continue à l’interface.",why:["En descendant dans l’huile, la pression augmente de ρhuileghhuile.","La pression est continue à l’interface ; on ajoute ensuite l’accroissement dans l’eau.","La hauteur équivalente exprime la pression totale comme une colonne d’eau fictive."],check:"La contribution de chaque couche doit être positive et proportionnelle à sa masse volumique et à son épaisseur."},
  manometer:{hypotheses:"Fluides au repos ; deux prises à la même cote ; eau et mercure non miscibles ; effets capillaires négligés.",why:["On chemine d’une prise à l’autre : la pression augmente en descendant et diminue en montant.","Les colonnes d’eau communes se compensent ; il reste l’effet de la différence de masse volumique.","Diviser par ρeaug convertit la différence de pression en mètres de colonne d’eau."],check:"Le côté où le mercure est le plus bas correspond à la pression la plus élevée."},
  planeForce:{hypotheses:"Paroi verticale plane, surface libre à pression atmosphérique, eau au repos, pression relative utilisée.",why:["La pression varie linéairement avec la profondeur ; le centre géométrique est à H/2.","La résultante est la pression au centre de gravité multipliée par l’aire.","Le moment quadratique décrit la répartition de la surface autour de son centre.","Comme la pression augmente vers le bas, le centre de poussée est sous le centre géométrique."],check:"Pour une paroi rectangulaire affleurante, yₚ = 2H/3 exactement."},
  submergedGate:{hypotheses:"Vanne verticale plane entièrement immergée ; liquide au repos ; pression atmosphérique identique des deux côtés hors liquide.",why:["La profondeur moyenne est celle du centre de gravité de la vanne.","On intègre la pression hydrostatique sur l’aire, ce qui donne F = ρgAȳ.","La position résulte de l’égalité des moments de la distribution de pression et de la résultante."],check:"Le centre de poussée doit être sous le centre de gravité, mais rester à l’intérieur de la vanne."},
  venturi:{hypotheses:"Écoulement permanent, eau incompressible, Venturi horizontal, fluide parfait et pertes négligées.",why:["On convertit les diamètres en mètres avant de calculer les sections circulaires.","Le manomètre fournit directement la différence de pression entre l’entrée et le col.","La conservation de la masse impose le même débit dans les deux sections.","Bernoulli traduit la conservation de l’énergie mécanique entre 1 et 2.","On remplace V₁ et V₂ par Q/S puis on isole Q dans l’équation obtenue.","La section du col étant plus petite, sa vitesse doit être plus grande."],check:"V₂/V₁ doit être égal à S₁/S₂ = (D₁/D₂)² et p₂ doit être inférieur à p₁."},
  torricelli:{hypotheses:"Réservoir de grande section, surface et orifice à pression atmosphérique, vitesse de surface négligeable.",why:["L’aire de l’orifice est calculée après conversion du diamètre en mètres.","Bernoulli donne √(2gh) ; le coefficient Cᵈ corrige la contraction et les pertes réelles.","Le débit volumique est le produit de la section par la vitesse moyenne réelle."],check:"Cᵈ < 1 implique une vitesse et un débit réels inférieurs aux valeurs idéales."},
  jetPlate:{hypotheses:"Régime permanent ; jet libre à pression atmosphérique ; plaque fixe ; pertes dans l’impact négligées pour le bilan axial.",why:["La section du jet se calcule avec son diamètre en mètres.","Le débit est constant jusqu’à l’impact.","Après déviation tangentielle, la composante de vitesse normale à la plaque devient nulle.","Le théorème de quantité de mouvement donne l’effort F = ρQV."],check:"L’effort varie comme V² : doubler la vitesse multiplie la force par quatre."},
  jetDeflect:{hypotheses:"Auget fixe, jet libre, norme de la vitesse conservée et pression atmosphérique à l’entrée comme à la sortie.",why:["Le débit permet d’obtenir le débit massique ṁ = ρQ.","La force est liée à la différence vectorielle entre les vitesses d’entrée et de sortie.","La géométrie du triangle des vitesses donne |ΔV| = 2V sin(θ/2)."],check:"À θ = 0°, la force tend vers zéro ; à θ = 180°, elle tend vers 2ρQV."},
  colebrook:{hypotheses:"Écoulement permanent établi dans une conduite circulaire pleine ; eau incompressible ; facteur de Darcy utilisé.",why:["On convertit D, Q, ε et ν en SI puis on déduit la vitesse moyenne.","Re compare l’inertie aux effets visqueux et détermine le régime.","En turbulent, Colebrook est implicite : on répète le calcul jusqu’à stabilisation de λ.","Darcy–Weisbach transforme le frottement réparti en perte de charge."],check:"λ est généralement compris entre 0,01 et 0,08 en conduite ; h_f doit être positive."},
  minorLosses:{hypotheses:"Écoulement permanent ; même diamètre et même vitesse de référence dans toutes les singularités.",why:["La vitesse moyenne se déduit du débit et de la section.","Les pertes locales s’additionnent lorsque les coefficients utilisent la même vitesse de référence.","Chaque singularité dissipe K·V²/(2g) ; la somme donne la perte totale."],check:"Les pertes varient comme V² : une réduction du débit est très efficace pour les diminuer."}
  ,froudeSimilarity:{hypotheses:"Similitude géométrique complète, même pesanteur sur le modèle et le prototype, écoulement à surface libre dominé par inertie et gravité.",why:["La similitude de Froude conserve le rapport entre forces d’inertie et de pesanteur.","Avec la même gravité, l’échelle des vitesses est la racine carrée de l’échelle des longueurs.","On applique cette échelle à la vitesse mesurée sur le modèle.","Un débit est une vitesse multipliée par une aire : λQ = λVλL².","Le débit modèle est d’abord converti de L/s en m³/s."],check:"Le prototype est plus grand : ses échelles de vitesse et de débit doivent être supérieures à 1."},
  manningChannel:{hypotheses:"Écoulement permanent uniforme, canal prismatique rectangulaire, pente faible et profondeur constante.",why:["Seules les parois en contact avec l’eau forment le périmètre mouillé ; la surface libre n’en fait pas partie.","Le rayon hydraulique représente l’efficacité hydraulique de la section.","En régime uniforme, la pente de fond égale la pente de la ligne d’énergie.","Le débit est la vitesse moyenne multipliée par la section mouillée.","Froude compare la vitesse de l’écoulement à la célérité des ondes de gravité."],check:"Fr < 1 indique un régime fluvial ; Fr > 1 un régime torrentiel ; Fr = 1 le régime critique."}
};

const equationSheets={density:["W = mg","ρ = m/𝒱","γ = ρg","d = ρ/ρeau"],viscosity:["τ = F/A","τ = μU/e","ν = μ/ρ"],coaxialViscometer:["ω = 2πN/60","U = ωRᵢ","τ = μU/e","C = τ(2πRᵢL)Rᵢ"],compressibility:["K = −Δp/(Δ𝒱/𝒱)","Δp = p₂−p₁"],capillary:["h = 4σcosθ/(ρgd)"],laplace:["Goutte : Δp = 2σ/R","Bulle : Δp = 4σ/R"],idealGas:["p = ρRT","T(K) = T(°C)+273,15"],pressureDepth:["p−pₐₜₘ = ρgh","pabs = pₐₜₘ+ρgh"],layeredPressure:["Δp = ρgΔh","p_fond = Σρᵢghᵢ"],manometer:["Descente : +ρgΔz","Montée : −ρgΔz"],hydraulicPress:["F₁/A₁ = F₂/A₂","A₁x₁ = A₂x₂"],planeForce:["F = ρgAȳ","yₚ = ȳ+Iᴳ/(Aȳ)"],submergedGate:["ȳ = y₀+H/2","F = ρgAȳ","yₚ = ȳ+Iᴳ/(Aȳ)"],circularGate:["A = πD²/4","Iᴳ = πD⁴/64","F = ρgAȳ"],bargeStability:["BM = I/∇","GM = KB+BM−KG","Stable si GM > 0"],venturi:["Q = S₁V₁ = S₂V₂","p/ρg+V²/2g+z = cte","Δp = (ρm−ρ)gΔh"],torricelli:["V = Cᵈ√(2gh)","Q = SV"],jetPlate:["ΣF⃗ = ṁ(V⃗₂−V⃗₁)","F = ρQV"],jetDeflect:["F = 2ρQVsin(θ/2)"],colebrook:["Re = VD/ν","1/√λ = −2log₁₀[ε/(3,7D)+2,51/(Re√λ)]","h_f = λ(L/D)V²/(2g)"],minorLosses:["h_s = ΣK·V²/(2g)"],froudeSimilarity:["Fr = V/√(gL)","λV = √λL","λQ = λL^(5/2)"],manningChannel:["R = A/P","V = KₛR^(2/3)√S","Fr = V/√(gy)"]};
const esc = value => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const parse = value => Number(String(value).trim().replace(",", ".").replace(/\s/g, ""));
const randomValue = v => Number((Math.round((v.min + Math.random() * (v.max - v.min)) / v.step) * v.step).toFixed(8));
const formatTime = seconds => `${String(Math.floor(seconds / 60)).padStart(2,"0")}:${String(seconds % 60).padStart(2,"0")}`;
const toast = text => { const el = document.querySelector("#toast"); el.textContent = text; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 1800); };

function home() {
  stopTimer(); state.exercise = null;
  app.innerHTML = `<section class="hero"><p class="eyebrow">Mécanique des fluides · Génie civil</p><h1>Comprendre, calculer, vérifier.</h1><p>Des exercices paramétriques fidèles au polycopié, avec unités, validation tolérante et correction raisonnée.</p><div class="signature">École Nationale d’Ingénieurs de Sfax<br><strong>Dr Ahmed Ksentini</strong></div></section><div class="section-title"><div><h2>Choisir un chapitre</h2><p>Une bibliothèque conçue pour s’enrichir progressivement.</p></div></div><section class="chapter-grid">${state.catalog.chapters.map(ch => { const count = state.catalog.exercises.filter(e => e.chapter === ch.id).length; return `<button class="chapter" data-chapter="${ch.id}"><span class="num">${ch.number}</span><h3>${esc(ch.title)}</h3><p>${esc(ch.description)}</p><span class="count">${count} exercice${count>1?"s":""} →</span></button>`; }).join("")}</section>`;
  document.querySelectorAll("[data-chapter]").forEach(button => button.addEventListener("click", () => chapterPage(button.dataset.chapter)));
  history.replaceState({}, "", location.pathname);
}

function chapterPage(chapterId) {
  const chapter = state.catalog.chapters.find(c => c.id === chapterId), exercises = state.catalog.exercises.filter(e => e.chapter === chapterId);
  app.innerHTML = `<button class="back" id="backHome">← Tous les chapitres</button><section class="chapter-banner"><span class="num">${chapter.number}</span><div><h1>${esc(chapter.title)}</h1><p>${esc(chapter.description)}</p></div></section><div class="section-title"><div><h2>Exercices</h2><p>Choisissez une situation puis un mode de travail.</p></div></div><section class="exercise-list">${exercises.map((e,i)=>`<button class="exercise-card" data-exercise="${e.id}"><span class="exercise-index">${String(i+1).padStart(2,"0")}</span><span><strong>${esc(e.title)}</strong><small>Niveau ${e.difficulty} · données paramétriques</small></span><span class="arrow">→</span></button>`).join("")}</section>`;
  document.querySelector("#backHome").addEventListener("click", home);
  document.querySelectorAll("[data-exercise]").forEach(b => b.addEventListener("click",()=>openExercise(state.catalog.exercises.find(e=>e.id===b.dataset.exercise))));
}

function openExercise(exercise, mode = state.mode) {
  stopTimer(); state.exercise = exercise; state.mode = mode; state.attempts = {};
  state.data = Object.fromEntries(exercise.variables.map(v => [v.key, mode === "learn" ? v.value : randomValue(v)]));
  renderExercise();
  if (mode === "exam") startTimer();
  history.replaceState({}, "", `#${exercise.id}`);
}

function renderExercise() {
  const e = state.exercise, chapter = state.catalog.chapters.find(c => c.id === e.chapter);
  app.innerHTML = `<section class="exercise-head"><div><button class="back" id="back">← Exercices du chapitre</button><h1>${esc(e.title)}</h1><p>Chapitre ${chapter.number} · Niveau ${e.difficulty}</p></div><div><div class="mode-switch" aria-label="Mode de travail">${Object.entries(modes).map(([key,label]) => `<button data-mode="${key}" class="${state.mode===key?"active":""}">${label}</button>`).join("")}</div><div id="clock" class="exam-clock">${state.mode === "exam" ? "Temps 00:00" : ""}</div></div></section><section class="workspace"><div><article class="card"><h2>Énoncé</h2><p class="statement">${esc(e.statement)}</p><div class="data-grid">${e.variables.map(v => `<div class="field"><label for="v_${v.key}">${esc(v.label)}</label><div class="input-wrap"><input id="v_${v.key}" data-variable="${v.key}" type="number" step="any" value="${state.data[v.key]}" ${state.mode === "exam" ? "readonly" : ""}><span class="unit">${v.unit}</span></div></div>`).join("")}</div><div class="actions">${state.mode !== "learn" ? `<button class="secondary" id="randomize">↻ Nouvelles données</button>` : ""}</div></article><article class="card"><h2>Schéma de l’exercice</h2><div class="diagram">${diagram(e.solver,state.data)}</div><p class="diagram-note">Schéma non à l’échelle. Les flèches indiquent les grandeurs et le sens positif.</p></article></div><div><article class="card"><h2>${state.mode === "exam" ? "Votre copie" : "Résolution guidée"}</h2><div id="questions">${e.questions.map((q,i) => question(q,i)).join("")}</div><div class="actions"><button class="primary" id="submitAll">${state.mode === "exam" ? "Rendre la copie" : "Tout vérifier"}</button>${state.mode !== "exam" ? `<button class="secondary" id="showCorrection">Voir la correction</button>` : ""}</div><div id="score"></div></article><article class="card correction" id="correction" hidden></article></div></section>`;
  const formulas=equationSheets[e.solver]||["Consulter les hypothèses et établir le bilan fondamental."];
  app.querySelector(".workspace > div:nth-child(2)").insertAdjacentHTML("afterbegin",`<article class="card equation-card"><h2>Équations utiles</h2><p class="equation-intro">Rappel littéral — identifiez chaque grandeur avant de remplacer les valeurs.</p>${formulas.map(f=>`<div class="equation-line">${esc(f)}</div>`).join("")}</article>`);
  bindExerciseEvents();
}

function question(q, i) { return `<div class="question"><div class="question-title">${i+1}. ${esc(q.label)}</div><div class="answer-row"><div class="input-wrap"><input id="a_${q.key}" data-answer="${q.key}" inputmode="decimal" autocomplete="off" placeholder="Votre réponse"><span class="unit">${q.unit}</span></div>${state.mode !== "exam" ? `<button class="ghost" data-check="${q.key}">Vérifier</button>` : ""}</div><p class="feedback" id="f_${q.key}"></p></div>`; }

function readData() { state.exercise.variables.forEach(v => state.data[v.key] = parse(document.querySelector(`#v_${v.key}`).value)); }
function check(key) {
  readData(); const target = solve(state.exercise, state.data).values[key], input = document.querySelector(`#a_${key}`), value = parse(input.value), feedback = document.querySelector(`#f_${key}`);
  state.attempts[key] = (state.attempts[key] || 0) + 1;
  const correct = isClose(value, target); feedback.className = `feedback ${correct ? "good" : "bad"}`;
  feedback.innerHTML = correct ? "✓ Correct — unité et ordre de grandeur cohérents." : `✕ À revoir.${state.mode === "learn" && state.attempts[key] > 1 ? `<span class="hint">Indice : commencez par convertir toutes les données en SI et écrivez la relation littérale.</span>` : ""}`;
  return correct;
}
function submitAll() {
  const correct = state.exercise.questions.filter(q => check(q.key)).length, total = state.exercise.questions.length, score = 20 * correct / total;
  document.querySelector("#score").innerHTML = `<p class="score">Résultat : ${correct}/${total} — ${score.toLocaleString("fr-FR",{maximumFractionDigits:1})}/20</p>`;
  if (state.mode === "exam") { stopTimer(); showCorrection(); document.querySelector("#showCorrection")?.remove(); }
}
function showCorrection() {
  readData(); const result = solve(state.exercise, state.data), box = document.querySelector("#correction");
  const guide = pedagogy[state.exercise.solver] || {hypotheses:"Grandeurs exprimées dans le Système International.",why:[],check:"Vérifier les unités et l’ordre de grandeur."};
  box.hidden = false; box.innerHTML = `<h2>Correction détaillée</h2><section class="reasoning"><h3>1. Hypothèses et modèle physique</h3><p>${esc(guide.hypotheses)}</p></section><section class="given-data"><h3>2. Données de l’énoncé</h3><div class="data-summary">${state.exercise.variables.map(v=>`<span><small>${esc(v.label)}</small><strong>${esc(state.data[v.key])} ${v.unit}</strong></span>`).join("")}</div><p class="method-note">Avant tout calcul, les millimètres, litres, bars et kilopascals sont convertis en unités SI. Le calcul littéral est écrit avant le remplacement numérique.</p></section><h3>3. Résolution raisonnée</h3>${result.steps.map((s,i) => `<div class="solution-step" data-step="${i+1}"><h3>${esc(s[0])}</h3>${guide.why[i]?`<p class="explanation">${esc(guide.why[i])}</p>`:""}<p class="formula">${esc(s[1])}</p></div>`).join("")}<div class="final-result"><strong>4. Résultats numériques</strong><br>${state.exercise.questions.map(q => `${esc(q.label)} = <strong>${Number(result.values[q.key]).toLocaleString("fr-FR",{maximumSignificantDigits:5})} ${q.unit}</strong>`).join("<br>")}</div><section class="sanity-check"><h3>5. Interprétation et contrôle</h3><p>${esc(guide.check)}</p><p>Contrôle d’unités : chaque résultat est donné dans l’unité demandée. Il faut toujours conserver davantage de chiffres pendant le calcul et n’arrondir qu’à la fin.</p></section>`; box.scrollIntoView({behavior:"smooth",block:"start"});
}
function bindExerciseEvents() {
  document.querySelector("#back").addEventListener("click", () => chapterPage(state.exercise.chapter));
  document.querySelectorAll("[data-mode]").forEach(b => b.addEventListener("click", () => openExercise(state.exercise, b.dataset.mode)));
  document.querySelectorAll("[data-variable]").forEach(input => input.addEventListener("change", () => { readData(); document.querySelector("#correction").hidden = true; }));
  document.querySelectorAll("[data-check]").forEach(b => b.addEventListener("click", () => check(b.dataset.check)));
  document.querySelector("#submitAll").addEventListener("click", submitAll);
  document.querySelector("#showCorrection")?.addEventListener("click", showCorrection);
  document.querySelector("#randomize")?.addEventListener("click", () => openExercise(state.exercise, state.mode));
}

function diagram(type,d) {
  const common = `viewBox="0 0 520 190" role="img" aria-label="Schéma de principe"`;
  if (type === "density") return `<svg ${common}><path d="M135 35h250l-25 130H160z" fill="#fde68a" stroke="#92400e" stroke-width="4"/><path d="M155 80h210" stroke="#f59e0b" stroke-width="5"/><text x="210" y="65">Huile · 𝒱=${d.volume} m³</text><path d="M260 105v48" stroke="#b91c1c" stroke-width="3"/><path d="M252 143l8 12 8-12" fill="#b91c1c"/><text x="275" y="135">W=${d.W} kN</text></svg>`;
  if (type === "pressureDepth") return `<svg ${common}><path d="M20 38h480v140H20z" fill="#bae6fd"/><path d="M20 38h480" stroke="#0369a1" stroke-width="4"/><circle cx="285" cy="132" r="15" fill="#f97316"/><path d="M285 45v72M277 48h16M277 117h16" stroke="#b91c1c" stroke-width="3"/><text x="300" y="85">h=${d.h} m</text><text x="30" y="28">Surface libre · pₐₜₘ</text><text x="310" y="140">plongeur · p</text></svg>`;
  if (type === "compressibility") return `<svg ${common}><defs><linearGradient id="pc"><stop stop-color="#bae6fd"/><stop offset="1" stop-color="#0284c7"/></linearGradient></defs><rect x="115" y="45" width="290" height="105" rx="8" fill="url(#pc)" stroke="#075985" stroke-width="4"/><path d="M70 97h55M450 97h-55" stroke="#b91c1c" stroke-width="5"/><path d="M118 89l12 8-12 8M402 89l-12 8 12 8" fill="#b91c1c"/><text x="175" y="85">p₁=${d.p1} bar</text><text x="285" y="120">p₂=${d.p2} bar</text><text x="178" y="173">Compression · volume diminue</text></svg>`;
  if (type === "layeredPressure") return `<svg ${common}><defs><linearGradient id="pw" y2="1"><stop stop-color="#7dd3fc"/><stop offset="1" stop-color="#0369a1"/></linearGradient></defs><path d="M100 25v145h250V25" fill="none" stroke="#334155" stroke-width="7"/><rect x="104" y="48" width="242" height="48" fill="#fde68a"/><rect x="104" y="96" width="242" height="70" fill="url(#pw)"/><path d="M370 48v48M370 96v70" stroke="#475569" stroke-width="2"/><text x="145" y="78">huile · ${d.hOil} m</text><text x="145" y="135">eau · ${d.hWater} m</text><text x="380" y="75">p augmente</text><text x="380" y="160">p fond</text></svg>`;
  if (type === "submergedGate") return `<svg ${common}><defs><linearGradient id="pg" x2="1"><stop stop-color="#dbeafe"/><stop offset="1" stop-color="#2563eb"/></linearGradient></defs><rect x="25" y="25" width="290" height="150" fill="#bae6fd"/><rect x="315" y="70" width="22" height="90" fill="#64748b"/><path d="M315 70h-55l55 90h-125z" fill="url(#pg)" opacity=".75"/><path d="M200 115h105" stroke="#b91c1c" stroke-width="5"/><path d="M300 107l13 8-13 8" fill="#b91c1c"/><path d="M360 25v45M360 70v90" stroke="#334155" stroke-width="2"/><text x="370" y="50">y₀=${d.y0} m</text><text x="370" y="120">H=${d.H} m</text><text x="205" y="105">F</text></svg>`;
  if (type === "torricelli") return `<svg ${common}><path d="M40 25v140h230V25" fill="none" stroke="#334155" stroke-width="7"/><rect x="44" y="45" width="222" height="116" fill="#7dd3fc"/><path class="flow-animate" d="M270 135h190" stroke="#0284c7" stroke-width="14" stroke-dasharray="18 9"/><path d="M300 45v90" stroke="#b91c1c" stroke-width="2"/><text x="315" y="92">h=${d.h} m</text><text x="330" y="125">d=${d.d} mm</text><text x="370" y="158">V = Cᵈ√2gh</text></svg>`;
  if (type === "jetDeflect") return `<svg ${common}><defs><marker id="jf" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0l8 4-8 4z" fill="#b91c1c"/></marker></defs><path class="flow-animate" d="M25 100h245q90 0 155-65" fill="none" stroke="#38bdf8" stroke-width="18" stroke-dasharray="20 10"/><path d="M270 100q75 0 135-55" fill="none" stroke="#475569" stroke-width="12"/><path d="M270 100l-70 55" stroke="#b91c1c" stroke-width="4" marker-end="url(#jf)"/><text x="75" y="80">V=${d.V} m/s</text><text x="330" y="90">θ=${d.theta}°</text><text x="185" y="175">force sur l’auget</text></svg>`;
  if (type === "minorLosses") return `<svg ${common}><path d="M25 125h105q25 0 25-25V55h115v70h70v-45h150" fill="none" stroke="#475569" stroke-width="20"/><path class="flow-animate" d="M25 125h105q25 0 25-25V55h115v70h70v-45h150" fill="none" stroke="#38bdf8" stroke-width="10" stroke-dasharray="18 10"/><path d="M20 30h470" stroke="#0f766e" stroke-width="3"/><path d="M20 30l470 105" stroke="#dc2626" stroke-width="3" stroke-dasharray="7 5"/><text x="25" y="22">Ligne de charge amont</text><text x="310" y="155">chutes à chaque singularité</text></svg>`;
  if (type === "froudeSimilarity") return `<svg ${common}><path d="M35 135q60-70 120 0t120 0" fill="#bae6fd" stroke="#0284c7" stroke-width="3"/><path d="M320 155q35-40 70 0t70 0" fill="#bae6fd" stroke="#0284c7" stroke-width="3"/><path d="M60 35h190M330 95h120" stroke="#334155" stroke-width="2"/><text x="85" y="28">Prototype</text><text x="350" y="88">Modèle 1/${d.N}</text><text x="80" y="170">Vₚ, Qₚ</text><text x="355" y="180">Vₘ=${d.Vm} m/s</text></svg>`;
  if (type === "manningChannel") return `<svg ${common}><path d="M70 35l70 125h240l70-125" fill="none" stroke="#475569" stroke-width="7"/><path d="M110 105h300l-31 55H141z" fill="#7dd3fc"/><path class="flow-animate" d="M145 132h225" stroke="#0284c7" stroke-width="5" stroke-dasharray="18 9"/><path d="M110 95v65M102 105h16M102 160h16" stroke="#b91c1c" stroke-width="2"/><text x="120" y="132">y=${d.y} m</text><text x="230" y="180">b=${d.b} m</text><text x="285" y="95">S=${d.S} ‰</text></svg>`;
  if (type === "venturi") return `<svg ${common}><defs><marker id="flow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0l8 4-8 4z" fill="#075985"/></marker></defs><path d="M20 42h145l80 38h75l80-38h100v106H400l-80-38h-75l-80 38H20z" fill="#bae6fd" stroke="#0369a1" stroke-width="4"/><path d="M55 95h400" stroke="#075985" stroke-width="3" marker-end="url(#flow)"/><path d="M105 147v24h255v-61" fill="none" stroke="#475569" stroke-width="7"/><path d="M125 164h215" stroke="#d97706" stroke-width="12"/><text x="35" y="30">Section 1 · D₁=${d.D1} mm</text><text x="230" y="68">Col 2 · D₂=${d.D2} mm</text><text x="175" y="186">Mercure · Δh=${d.h} mm</text><text x="400" y="88">écoulement</text></svg>`;
  if (type === "manometer") return `<svg ${common}><path d="M145 25v110q0 35 35 35h155q35 0 35-35V25" fill="none" stroke="#475569" stroke-width="18"/><path d="M154 98v37q0 26 26 26h155q26 0 26-26V68" fill="none" stroke="#d97706" stroke-width="12"/><path d="M385 70v28M378 70h14M378 98h14" stroke="#b91c1c" stroke-width="2"/><text x="70" y="30">Prise 1 · p₁</text><text x="380" y="30">Prise 2 · p₂</text><text x="395" y="91">Δh=${d.h} mm</text><text x="190" y="148">mercure</text></svg>`;
  if (type === "planeForce") return `<svg ${common}><path d="M30 35h280v135H30z" fill="#bae6fd"/><path d="M310 25v150" stroke="#334155" stroke-width="12"/><path d="M80 48h210M80 80h210M80 112h210M80 144h210" stroke="#0284c7" stroke-width="2"/><path d="M130 55h150M130 90h150M130 130h150" stroke="#0f766e" stroke-width="4" marker-end="url(#a)"/><defs><marker id="a" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0l6 3-6 3z" fill="#0f766e"/></marker></defs></svg>`;
  if (type === "jetPlate") return `<svg ${common}><path class="flow-animate" d="M30 95h270" stroke="#0284c7" stroke-width="24" stroke-dasharray="20 10"/><path d="M310 25v140" stroke="#334155" stroke-width="14"/><path d="M300 90q60-5 90-55M300 100q60 5 90 55" fill="none" stroke="#7dd3fc" stroke-width="13"/><path d="M310 95H215" stroke="#b91c1c" stroke-width="4"/><text x="90" y="70">V=${d.V} m/s</text><text x="210" y="120">F = ρQV</text></svg>`;
  return `<svg ${common}><path d="M30 55h450v80H30z" fill="#bae6fd" stroke="#475569" stroke-width="7"/><path d="M70 95h360" stroke="#0284c7" stroke-width="4" stroke-dasharray="12 8"/><text x="205" y="45">L · D · ε</text></svg>`;
}
function startTimer() { state.seconds = 0; state.timer = setInterval(() => { state.seconds++; const clock = document.querySelector("#clock"); if (clock) clock.textContent = `Temps ${formatTime(state.seconds)}`; }, 1000); }
function stopTimer() { clearInterval(state.timer); state.timer = null; }

document.querySelector("#homeButton").addEventListener("click", home);
window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); state.installPrompt = event; const b = document.querySelector("#installButton"); b.hidden = false; b.onclick = async () => { await state.installPrompt.prompt(); b.hidden = true; }; });
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));

try { const [catalog,batch12,batch34]=await Promise.all([fetch("./data/exercises.json").then(r=>r.json()),fetch("./data/exercises-ch1-ch2.json").then(r=>r.json()),fetch("./data/exercises-ch3-ch4.json").then(r=>r.json())]); state.catalog={...catalog,exercises:[...catalog.exercises,...batch12,...batch34]}; const requested=state.catalog.exercises.find(e=>`#${e.id}`===location.hash); requested?openExercise(requested):home(); }
catch { app.innerHTML = `<section class="card"><h1>Chargement impossible</h1><p>Lancez l’application depuis un serveur web local ou depuis Cloudflare Pages.</p></section>`; }
