import { defaultSizing, defaultNpsh, defaultNetwork, solveSizing, solveNpsh, solveNetwork } from './engineering-solvers.js';
import { getInstallation, applyInstallationDiameter } from './installation.js';
import { solveInstallation } from './installation-solver.js';
import { loadProject, saveProject } from './project-store.js';
import { downloadReport } from './pdf-report.js';

const esc = x => String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n = x => Number(x).toLocaleString('fr-FR',{maximumSignificantDigits:5});
const titles = {dimensionnement:'Dimensionnement des conduites',npsh:'Aspiration et NPSH',reseau:'Réseau ramifié'};
const defaults = {dimensionnement:defaultSizing,npsh:defaultNpsh,reseau:defaultNetwork};
const solvers = {dimensionnement:solveSizing,npsh:solveNpsh,reseau:solveNetwork};
const projects = Object.fromEntries(Object.entries(defaults).map(([k,f])=>[k,loadProject(k,f,solvers[k])]));
const field = (key,label,value,unit='') => `<label class="plant-field"><span>${label}</span><div><input type="number" step="any" data-eng="${key}" value="${esc(value)}"><span>${unit}</span></div></label>`;
const fluids = p => field('rho','Masse volumique ρ',p.rho,'kg/m³')+field('nu','Viscosité cinématique ν',p.nu,'10⁻⁶ m²/s');
const pipeFields = p => field('flow','Débit',p.flow,'L/s')+field('length','Longueur',p.length,'m')+field('roughness','Rugosité ε',p.roughness,'mm')+field('sumK','Somme des coefficients K',p.sumK);
const metric = (label,value,unit) => `<article><span>${label}</span><strong>${n(value)} <small>${unit}</small></strong></article>`;
const table = (headers,rows) => `<div class="plant-table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const verdict = (ok,text) => `<p class="eng-verdict ${ok?'eng-pass':'eng-fail'}">${text}</p>`;
const regimeNote = rows => rows.some(r=>r.Re>=2000&&r.Re<4000)?'<p class="plant-warnings">Régime de transition détecté (Re 2 000–4 000) : pertes indicatives, choix à confirmer.</p>':'';
const notes = {
  dimensionnement:`Le plus petit diamètre intérieur de la liste satisfaisant V ≤ Vmax et h ≤ hmax est proposé. Les valeurs initiales sont une liste illustrative, pas un catalogue DN : saisir les diamètres intérieurs réels du fabricant (matériau, série, épaisseur). La rugosité est saisie explicitement, à adapter au matériau et à son état. P = ρgQh représente seulement la puissance hydraulique dissipée, pas la puissance moteur. Le choix ne vérifie ni pression nominale, ni tenue mécanique, ni coût, ni coups de bélier.`,
  npsh:`NPSHA = (p surface absolue − p vapeur absolue)/(ρg) + z surface − z référence pompe − h aspiration. Surface du réservoir de vitesse négligeable ; aucune pompe en amont. Les pertes incluent uniquement la conduite d’aspiration et ses accessoires. NPSHR doit provenir du fabricant au débit, à la vitesse de rotation et au liquide étudiés. La marge additive est choisie par l’utilisateur : 1 m est un exemple, pas une prescription universelle. NPSHA ≥ NPSHR + marge est un critère de présélection, pas une garantie d’absence de cavitation. Pressions initiales : eau vers 20 °C, atmosphère standard ; vérifier température et altitude.`,
  reseau:`Arbre à une source de charge piézométrique imposée (réservoir ou collecteur), sans boucle ni pompe interne. Un tronçon relie chaque parent au nœud. Q tronçon = demande locale + demandes descendantes ; H nœud = H parent − h tronçon ; p/(ρg) = H − z. Modèle nodal de réseau sous pression, énergie cinétique nodale négligée ; les K sont saisis par tronçon. Les demandes sont imposées et restent calculées même si la pression est insuffisante : le résultat signale alors un scénario non réalisable sous ces hypothèses, sans simuler le débit réellement fourni. Une source SOURCE existe implicitement. Les cotes et charges partagent le même repère.`
};

export function mountEngineering(root,kind,navigate) {
  const p=projects[kind];
  window.scrollTo(0,0);
  root.classList.add('plant-root');
  let fields=fluids(p);
  if(kind==='dimensionnement')fields+=pipeFields(p)+field('maxVelocity','Vitesse maximale',p.maxVelocity,'m/s')+field('maxLoss','Perte totale admissible',p.maxLoss,'m')+`<label class="plant-field"><span>Diamètres intérieurs réels (mm), séparés par ;</span><textarea id="engDiameters" rows="3">${esc(p.diameters.join('; '))}</textarea></label>`;
  if(kind==='npsh')fields+=pipeFields(p)+field('diameter','Diamètre intérieur aspiration',p.diameter,'mm')+field('surfacePressure','Pression absolue du réservoir',p.surfacePressure,'kPa abs')+field('vaporPressure','Pression de vapeur à la température étudiée',p.vaporPressure,'kPa abs')+field('surfaceZ','Cote surface du réservoir',p.surfaceZ,'m')+field('pumpZ','Cote de référence NPSH pompe',p.pumpZ,'m')+field('required','NPSH requis fabricant au débit étudié',p.required,'m')+field('margin','Marge additive choisie',p.margin,'m');
  if(kind==='reseau')fields+=field('sourceHead','Charge piézométrique SOURCE',p.sourceHead,'m')+field('minPressure','Pression minimale de service',p.minPressure,'m de liquide');
  root.innerHTML=`<section class="plant-app"><header class="plant-head"><div><button class="back" id="engBack">← Bureau de calcul</button><p class="plant-kicker">OUTILS D’INGÉNIERIE · LIQUIDE INCOMPRESSIBLE</p><h1>${titles[kind]}</h1><p>Calcul permanent · données modifiables · contrôle des hypothèses</p></div><div class="plant-tools"><button id="engSave">Exporter JSON</button><label class="ghost plant-import">Ouvrir JSON<input id="engImport" type="file" accept=".json,application/json"></label><button id="engPrint">Imprimer</button><button id="engReset">Exemple initial</button></div></header>
  <nav class="eng-tabs" aria-label="Modules avancés">${Object.entries(titles).map(([k,t])=>`<button data-eng-tab="${k}" ${k===kind?'aria-current="page"':''}>${t}</button>`).join('')}<button data-eng-tab="installation">Installation en série</button></nav><p id="engMessage" role="status"></p>
  <div class="plant-layout"><aside class="plant-settings software-panel"><h2>Données et critères</h2>${fields}</aside><div class="plant-work">
  ${kind==='reseau'?'<section class="software-panel"><h2>Tronçons et demandes</h2><p>Parent : SOURCE ou identifiant d’un autre nœud. La demande est le prélèvement local, pas le débit du tronçon.</p><div id="engNodes"></div><button id="engAdd">+ Nœud</button></section>':`<section class="software-panel"><h2>Lien avec l’installation en série</h2><label class="plant-field"><span>Tronçon à reprendre${kind==='npsh'?' — choisir uniquement une aspiration réelle':''}</span><select id="engTarget">${getInstallation().sections.map((s,i)=>`<option value="${i}">T${i+1} · ${esc(s.name)}</option>`).join('')}</select></label><button id="engLoadPipe">Reprendre les données de ce tronçon</button><p class="plant-help">Le transfert reprend le débit calculé, le liquide, la géométrie et les K. ${kind==='npsh'?'Les cotes, pressions et le NPSHR restent à renseigner.':'Les critères et la liste de diamètres restent inchangés.'}</p></section>`}
  <section id="engResults" aria-live="polite"></section><details class="software-panel plant-note" open><summary>Hypothèses, méthode et limites</summary><p>${notes[kind]}</p><p>Pertes : Darcy–Weisbach + ΣK V²/(2g), λ = 64/Re en laminaire et Colebrook–White à partir de Re = 2 000 (transition indicative jusqu’à 4 000).</p><p>Références : <a href="https://www.epa.gov/water-research/epanet" target="_blank" rel="noopener">EPA — modèles de réseaux</a> ; <a href="https://www.ksb.com/en-global/centrifugal-pump-lexicon/n" target="_blank" rel="noopener">KSB — NPSH</a>. Ce module utilise son propre solveur, pas EPANET.</p></details></div></div></section>`;
  root.querySelector('#engBack').onclick=()=>navigate('LOSSES_COLEBROOK_01');
  const studioButton=document.createElement('button');studioButton.textContent='Atelier graphique · réseaux maillés';studioButton.onclick=()=>navigate('atelier');root.querySelector('.eng-tabs').append(studioButton);
  const pdfButton=document.createElement('button');pdfButton.textContent='Rapport PDF';pdfButton.id='engPDF';pdfButton.onclick=()=>{try{downloadReport(titles[kind],p,solvers[kind](p),[notes[kind],'Unites : Q en L/s ; longueurs/cotes/pertes en m ; diametres et rugosites en mm ; nu en 10^-6 m2/s ; rho en kg/m3 ; pressions absolues en kPa pour NPSH.']);message('Rapport PDF généré.');}catch(e){message(e.message);}};root.querySelector('.plant-tools').append(pdfButton);
  const savedStatus=document.createElement('p');savedStatus.className='plant-help';savedStatus.id='engAutosave';root.querySelector('.plant-head').after(savedStatus);
  root.querySelectorAll('[data-eng-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.engTab));
  root.querySelectorAll('[data-eng]').forEach(el=>el.oninput=()=>{p[el.dataset.eng]=el.valueAsNumber;update();});
  root.querySelector('#engDiameters')?.addEventListener('input',e=>{p.diameters=e.target.value.split(/[;\s]+/).filter(Boolean).map(x=>Number(x.replace(',','.')));update();});
  const message = text => root.querySelector('#engMessage').textContent=text;
  root.querySelector('#engReset').onclick=()=>{projects[kind]=defaults[kind]();mountEngineering(root,kind,navigate);};
  root.querySelector('#engPrint').onclick=()=>{try{solvers[kind](p);root.querySelector('details').open=true;window.print();}catch(e){message('Impression suspendue : '+e.message);}};
  root.querySelector('#engSave').onclick=()=>{
    try{solvers[kind](p);const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,module:kind,data:p},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`mecaflu-${kind}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Projet exporté.');}catch(e){message(e.message);}
  };
  root.querySelector('#engImport').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>200000)throw Error('Maximum 200 Ko.');const x=JSON.parse(await file.text());if(x.version!==1||x.module!==kind)throw Error('Fichier d’un autre module ou version inconnue.');solvers[kind](x.data);projects[kind]=x.data;mountEngineering(root,kind,navigate);}catch(error){message(error.message);}};
  root.querySelector('#engLoadPipe')?.addEventListener('click',()=>{
    try{const installation=getInstallation(),r=solveInstallation(installation);if(!r.converged)throw Error('Installation non convergée : transfert suspendu.');const s=installation.sections[Number(root.querySelector('#engTarget').value)];Object.assign(p,{flow:r.flow,rho:installation.rho,nu:installation.nu,length:s.length,roughness:s.roughness,sumK:s.accessories.reduce((v,a)=>v+a.count*a.k,0)});if(kind==='npsh')p.diameter=s.diameter;root.querySelectorAll('[data-eng]').forEach(el=>el.value=p[el.dataset.eng]);update();message('Données reprises ; vérifier les critères et les hypothèses spécifiques.');}catch(e){message(e.message);}
  });
  function renderNodes(){
    root.querySelector('#engNodes').innerHTML=p.nodes.map((node,i)=>`<article class="plant-pipe"><header><h3>Tronçon vers ${esc(node.id)}</h3><button data-delete="${i}" ${p.nodes.length===1?'disabled':''}>Retirer</button></header><div class="eng-node-fields">${[['id','Identifiant',''],['parent','Parent',''],['demand','Prélèvement local','L/s'],['z','Cote','m'],['length','Longueur','m'],['diameter','D intérieur','mm'],['roughness','Rugosité','mm'],['sumK','Somme K','']].map(([key,label,unit])=>`<label class="plant-field"><span>${label}</span><div><input data-node="${i}" data-key="${key}" type="${['id','parent'].includes(key)?'text':'number'}" step="any" value="${esc(node[key])}"><span>${unit}</span></div></label>`).join('')}</div></article>`).join('');
    root.querySelectorAll('[data-node]').forEach(el=>el.oninput=()=>{p.nodes[Number(el.dataset.node)][el.dataset.key]=el.type==='number'?el.valueAsNumber:el.value.trim();update();});
    root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{p.nodes.splice(Number(b.dataset.delete),1);renderNodes();update();});
  }
  if(kind==='reseau'){
    renderNodes();root.querySelector('#engAdd').onclick=()=>{if(p.nodes.length>=50){message('Maximum 50 nœuds.');return;}let i=1;while(p.nodes.some(x=>x.id===`N${i}`))i++;p.nodes.push({id:`N${i}`,parent:'SOURCE',demand:1,z:0,length:50,diameter:100,roughness:0.05,sumK:0});renderNodes();update();};
  }
  function update(){
    const box=root.querySelector('#engResults');
    try{
      const r=solvers[kind](p);
      root.querySelector('#engAutosave').textContent=saveProject(kind,p)?'Dernier calcul valide sauvegardé automatiquement sur cet appareil. Exporter le JSON pour une copie externe.':'Stockage local indisponible : exporter le JSON avant de fermer.';
      if(kind==='dimensionnement'){
        box.innerHTML=verdict(!!r.selected,r.selected?`Diamètre proposé : ${n(r.selected.diameter)} mm intérieur`:'Aucun diamètre de la liste ne satisfait les deux critères.')+regimeNote(r.rows)+`<section class="software-panel"><h2>Comparaison des diamètres</h2>${table(['D intérieur (mm)','V (m/s)','Re','Pertes (m)','P dissipée (kW)','Critères'],r.rows.map(x=>[n(x.diameter),n(x.V),n(x.Re),n(x.total),n(x.power),x.accepted?'Satisfaits':'Non satisfaits']))}${r.selected?'<button id="engApply">Appliquer le diamètre proposé au tronçon sélectionné</button>':''}</section>`;
        box.querySelector('#engApply')?.addEventListener('click',()=>{try{const i=Number(root.querySelector('#engTarget').value);applyInstallationDiameter(i,r.selected.diameter);message(`Diamètre ${n(r.selected.diameter)} mm appliqué à T${i+1}. Recalculer l’installation et enregistrer son JSON pour conserver ce changement.`);}catch(e){message(e.message);}});
      }
      if(kind==='npsh')box.innerHTML=`<div class="plant-metrics">${metric('NPSH disponible',r.available,'m')}${metric('NPSH requis',p.required,'m')}${metric('Réserve disponible − requis',r.reserve,'m')}${metric('Cote pompe maximale selon critère',r.maxPumpZ,'m')}</div>`+verdict(r.accepted,r.accepted?'Critère NPSHA ≥ NPSHR + marge satisfait — validation fabricant nécessaire.':'Critère NPSH non satisfait : revoir l’aspiration ou le choix de pompe.')+regimeNote([r.loss])+`<section class="software-panel"><h2>Bilan d’aspiration</h2>${table(['Terme','Valeur'],[['(p surface − p vapeur)/(ρg)',`${n(r.pressureHead)} m`],['z surface − z pompe',`${n(p.surfaceZ-p.pumpZ)} m`],['Pertes aspiration',`${n(r.loss.total)} m`],['Vitesse aspiration',`${n(r.loss.V)} m/s`],['Marge imposée',`${n(p.margin)} m`]])}</section>`;
      if(kind==='reseau')box.innerHTML=`<div class="plant-metrics">${metric('Débit fourni par SOURCE',r.totalFlow,'L/s')}${metric('Charge source minimale selon critères',r.minSourceHead,'m')}${metric('Déficit de charge source',Math.max(0,r.minSourceHead-p.sourceHead),'m')}${metric('Résidu de continuité',r.continuityResidual,'L/s')}</div>`+verdict(r.accepted,r.accepted?'Pressions nodales minimales satisfaites aux demandes imposées.':'Pression insuffisante : les demandes imposées ne sont pas validées.')+regimeNote(r.rows.map(x=>x.loss))+`<section class="software-panel"><h2>Arborescence et bilan nodal</h2><p>Chaque ligne représente un tronçon parent → nœud, et la pression à son extrémité.</p>${table(['Parent → nœud','Q (L/s)','V (m/s)','Perte (m)','H (m)','p/(ρg) (m)','p relative (bar)','Critère'],r.rows.map(x=>[`${'↳ '.repeat(x.depth)}${esc(x.parent)} → ${esc(x.id)}`,n(x.flow),n(x.loss.V),n(x.loss.total),n(x.head),n(x.pressureHead),n(x.pressureBar),x.accepted?'Satisfait':'Insuffisant']))}</section>`;
    }catch(e){root.querySelector('#engAutosave').textContent='Saisie invalide : dernière sauvegarde valide conservée.';box.innerHTML=`<div class="calc-error" role="alert"><strong>Calcul suspendu</strong><p>${esc(e.message)}</p></div>`;}
  }
  update();
}
